export type Database = {
  public: {
    Tables: {
      paises: { Row: { id: string; codigo: string; nombre: string; created_at: string }; Insert: { id?: string; codigo: string; nombre: string; created_at?: string }; Update: { id?: string; codigo?: string; nombre?: string; created_at?: string } };
      estandares: { Row: { id: string; codigo: string; nombre: string; pais_id: string; created_at: string }; Insert: { id?: string; codigo: string; nombre: string; pais_id: string; created_at?: string }; Update: { id?: string; codigo?: string; nombre?: string; pais_id?: string; created_at?: string } };
      divisiones: { Row: { id: string; codigo: string; nombre: string; estandar_id: string; created_at: string }; Insert: { id?: string; codigo: string; nombre: string; estandar_id: string; created_at?: string }; Update: { id?: string; codigo?: string; nombre?: string; estandar_id?: string; created_at?: string } };
      tags: { Row: { id: string; nombre: string; dimension: string; created_at: string }; Insert: { id?: string; nombre: string; dimension: string; created_at?: string }; Update: { id?: string; nombre?: string; dimension?: string; created_at?: string } };
      partidas: { Row: { id: string; nombre: string; descripcion: string | null; unidad: string; division_id: string; created_at: string }; Insert: { id?: string; nombre: string; descripcion?: string | null; unidad: string; division_id: string; created_at?: string }; Update: { id?: string; nombre?: string; descripcion?: string | null; unidad?: string; division_id?: string; created_at?: string } };
      partida_tags: { Row: { partida_id: string; tag_id: string; created_at: string }; Insert: { partida_id: string; tag_id: string; created_at?: string }; Update: { partida_id?: string; tag_id?: string; created_at?: string } };
      partida_localizaciones: { Row: { id: string; partida_id: string; estandar_id: string; codigo_local: string; referencia: string | null; created_at: string }; Insert: { id?: string; partida_id: string; estandar_id: string; codigo_local: string; referencia?: string | null; created_at?: string }; Update: { id?: string; partida_id?: string; estandar_id?: string; codigo_local?: string; referencia?: string | null; created_at?: string } };
      revit_categorias: { Row: { id: string; nombre: string; created_at: string }; Insert: { id?: string; nombre: string; created_at?: string }; Update: { id?: string; nombre?: string; created_at?: string } };
      revit_mapeos: { Row: { id: string; categoria_id: string; partida_id: string; formula_metrado: string | null; created_at: string }; Insert: { id?: string; categoria_id: string; partida_id: string; formula_metrado?: string | null; created_at?: string }; Update: { id?: string; categoria_id?: string; partida_id?: string; formula_metrado?: string | null; created_at?: string } };
      proyectos: { Row: { id: string; nombre: string; descripcion: string | null; pais_id: string; estandar_id: string; estado: string; usuario_id: string; created_at: string; updated_at: string }; Insert: { id?: string; nombre: string; descripcion?: string | null; pais_id: string; estandar_id: string; estado?: string; usuario_id: string; created_at?: string; updated_at?: string }; Update: { id?: string; nombre?: string; descripcion?: string | null; pais_id?: string; estandar_id?: string; estado?: string; usuario_id?: string; created_at?: string; updated_at?: string } };
      proyecto_partidas: { Row: { id: string; proyecto_id: string; partida_id: string; metrado: number; created_at: string; updated_at: string }; Insert: { id?: string; proyecto_id: string; partida_id: string; metrado: number; created_at?: string; updated_at?: string }; Update: { id?: string; proyecto_id?: string; partida_id?: string; metrado?: number; created_at?: string; updated_at?: string } };
      proyecto_miembros: { Row: { id: string; proyecto_id: string; usuario_id: string; rol: string; created_at: string }; Insert: { id?: string; proyecto_id: string; usuario_id: string; rol: string; created_at?: string }; Update: { id?: string; proyecto_id?: string; usuario_id?: string; rol?: string; created_at?: string } };
      bim_importaciones: { Row: { id: string; proyecto_id: string; archivo_nombre: string; elementos_importados: number; estado: string; usuario_id: string; created_at: string }; Insert: { id?: string; proyecto_id: string; archivo_nombre: string; elementos_importados: number; estado?: string; usuario_id: string; created_at?: string }; Update: { id?: string; proyecto_id?: string; archivo_nombre?: string; elementos_importados?: number; estado?: string; usuario_id?: string; created_at?: string } };
      bim_elementos: { Row: { id: string; importacion_id: string; categoria_revit: string; familia: string; tipo: string; area: number | null; volumen: number | null; longitud: number | null; cantidad: number | null; parametros: Record<string, unknown> | null; partida_id: string | null; created_at: string }; Insert: { id?: string; importacion_id: string; categoria_revit: string; familia: string; tipo: string; area?: number | null; volumen?: number | null; longitud?: number | null; cantidad?: number | null; parametros?: Record<string, unknown> | null; partida_id?: string | null; created_at?: string }; Update: { id?: string; importacion_id?: string; categoria_revit?: string; familia?: string; tipo?: string; area?: number | null; volumen?: number | null; longitud?: number | null; cantidad?: number | null; parametros?: Record<string, unknown> | null; partida_id?: string | null; created_at?: string } };
      partida_sugerencias: { Row: { id: string; proyecto_id: string; nombre: string; descripcion: string | null; unidad: string; tipo_proyecto: string | null; fase: string | null; estado: string; usuario_id: string; created_at: string; updated_at: string }; Insert: { id?: string; proyecto_id: string; nombre: string; descripcion?: string | null; unidad: string; tipo_proyecto?: string | null; fase?: string | null; estado?: string; usuario_id: string; created_at?: string; updated_at?: string }; Update: { id?: string; proyecto_id?: string; nombre?: string; descripcion?: string | null; unidad?: string; tipo_proyecto?: string | null; fase?: string | null; estado?: string; usuario_id?: string; created_at?: string; updated_at?: string } };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
